### ISSUE TITLE
How much time it might take to publish the codes?

### ISSUE THREAD

**Issue by SamihaSara** [ISosnovik/SiamSE#1]

**Comment by ISosnovik** [comment]
Hello @SamihaSara. It will take some time for us to finalize the code. In the meantime, you can check https://github.com/ISosnovik/sesn. It contains the implementation of scale-convolution. Thus, by using the recipe from our paper and the provided repo, you can try to reproduce the results of SE-SiamFC.

**Comment by ISosnovik** [comment]
Done

**Comment by vstracksj** [comment]
Hello,I meet the problem when I train the model with the GOT10k dataset,and it interrupted with the error "TYPEERROR: dataparallel object is not iterable"? Does something that about multiple gpus has to handle?

**Comment by ISosnovik** [comment]
Duplicate of #2
