### ISSUE TITLE
problems when train model 

### ISSUE THREAD

**Issue by vstracksj** [ISosnovik/SiamSE#2]
when  I try to train the model guided by the readme.md ,it interruptted with an error "DataParallel is not iterable".Could you please assist to solve it? Thank you very much!!!

**Comment by ISosnovik** [comment]
Could you provide the whole error message?

Make sure, that 
1) got10k is downloaded
2) the corresponding paths are set correctly in the config file

**Comment by vstracksj** [comment]
yeah,the got10k dataset is downloaded and processed followed the guidance,

>>PROGRESS：2.00%
Epoch:[1][9375/9375]lr:0.100000 Batch time:0.200s Loss:0.29124
Progress:9375/468750[2%],speed:0.200s/iter,ETA 1:01:28(D:H:M)
PROGRESS:2.00%
Trackback (most recent call last):
   File "train_siamfc.py",line 64,in <module>
    epoch=epoch+1,cur_lr=cur_lr,cfg=config)
TypeError:'DataParallel' object is not iterable

**Comment by ISosnovik** [comment]
It's fixed now. Please check the latest commit

**Comment by lucky-dersan** [comment]
i want to track multi objects, this project can solve it?

**Comment by amoskalev** [comment]
> i want to track multi objects, this project can solve it?

Our model is build primary for single object tracking. Although, you can still try do multi-object by running several instances of SE-SiamFC
